name: dev-container image build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: dev-container image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          tags: ghcr.io/roni1993/dev-container:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
